// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PocheteDados.Data;

#nullable disable

namespace PocheteAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PocheteModelos.Modelo.Admin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("PocheteModelos.Modelo.Curso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int>("ProfessorMatricula")
                        .HasColumnType("int");

                    b.Property<long>("TurmaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorMatricula")
                        .IsUnique();

                    b.HasIndex("TurmaId")
                        .IsUnique();

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("PocheteModelos.Modelo.DadosTemporarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Conteudo1")
                        .HasColumnType("int");

                    b.Property<long?>("Conteudo2")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("DadosTemporarios");
                });

            modelBuilder.Entity("PocheteModelos.Modelo.Movimentacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataRetirada")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PocheteId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ProfessorMatricula")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PocheteId");

                    b.HasIndex("ProfessorMatricula");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("PocheteModelos.Modelo.Pochete", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("IdToken")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("SalaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SalaId");

                    b.ToTable("Pochetes");
                });

            modelBuilder.Entity("PocheteModelos.Modelo.Professor", b =>
                {
                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Matricula");

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("PocheteModelos.Modelo.Sala", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("PocheteModelos.Modelo.Turma", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("PocheteModelos.Modelo.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PocheteModelos.Modelo.Curso", b =>
                {
                    b.HasOne("PocheteModelos.Modelo.Professor", "Professor")
                        .WithOne()
                        .HasForeignKey("PocheteModelos.Modelo.Curso", "ProfessorMatricula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocheteModelos.Modelo.Turma", "Turma")
                        .WithOne()
                        .HasForeignKey("PocheteModelos.Modelo.Curso", "TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("PocheteModelos.Modelo.Movimentacao", b =>
                {
                    b.HasOne("PocheteModelos.Modelo.Pochete", "Pochete")
                        .WithMany()
                        .HasForeignKey("PocheteId")
                        .HasPrincipalKey("IdToken")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PocheteModelos.Modelo.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorMatricula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pochete");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("PocheteModelos.Modelo.Pochete", b =>
                {
                    b.HasOne("PocheteModelos.Modelo.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sala");
                });
#pragma warning restore 612, 618
        }
    }
}
